services:
  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379


  app:
    container_name: seo_app
    restart: always

    build:
      context: .
      dockerfile: Dockerfile
    
    command: >
      sh -c " python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

    volumes:
      - static_volume:/app/staticfiles
      - type: bind
        source: .
        target: /app


  db:
    image: mysql:8.0
    container_name: db_seo_app
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD='true'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_seo_app
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80

  celery:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: celery_seo_app
    command: celery -A core.celery worker -l info
    volumes:
        - .:/app/
    environment:
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
        - db
        - redis
        - app

volumes:
  db:
  static_volume:
  celery:
